server:
  port: 8601

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/warehouse
    username: springuser
    password: SpringUser
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        jdbc:
          timezone: UTC
  output:
    ansi:
      enabled: DETECT

logging:
  file:
    name: logs/application-log.log
  level:
    root: error
    org.springframework.web: error
    com.kata.warehouse_accounting: debug
    org.hibernate: error
  pattern:
    dateformat: yy-MM-dd HH:mm:ss
