server:
  port: 8601

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/warehouse
    # CREATE ROLE springuser WITH
    #	LOGIN
    #	SUPERUSER
    #	CREATEDB
    #	CREATEROLE
    #	INHERIT
    #	REPLICATION
    #	CONNECTION LIMIT -1
    #	PASSWORD 'SpringUser';
    username: springuser
    password: SpringUser

  jpa:
    hibernate:
      ddl-auto: update
